//! The Rust tool has to produce exactly what the Python tool it replaced
//! produced, byte for byte: `README.md` and `languages.json` are both checked
//! in, so any difference in formatting would show up as a diff the first time
//! someone ran this.
//!
//! The fixtures were generated by the Python tool itself. They cover the cases
//! where the two could plausibly disagree: thousands separators, emoji (which
//! Python escapes as `\uXXXX`, including surrogate pairs), a repository with
//! no description, languages tied on star count, and a non-GitHub URL.

use std::fs;
use std::path::{Path, PathBuf};

use langs_in_rust::{languages, readme};

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

#[test]
fn renders_the_readme_the_way_python_did() {
    let languages = languages::load(&fixture(languages::PATH)).unwrap();
    let expected = fs::read_to_string(fixture(readme::PATH)).unwrap();

    assert_eq!(readme::render(&languages), expected);
}

#[test]
fn writes_the_language_list_the_way_python_did() {
    let expected = fs::read_to_string(fixture(languages::PATH)).unwrap();
    let languages = languages::load(&fixture(languages::PATH)).unwrap();

    assert_eq!(languages::to_json(&languages).unwrap(), expected);
}
