//! `README.md` and `languages.json` are both checked in, so the exact bytes
//! this tool writes matter: a change in how either is rendered would show up
//! as a diff across the whole file rather than in the entries that changed.
//!
//! These fixtures were generated by the Python tool this one replaced, and
//! pin the format it established. They cover the cases where an
//! implementation could plausibly drift: thousands separators, emoji (escaped
//! as `\uXXXX`, including surrogate pairs), a repository with no description,
//! languages tied on star count, and a non-GitHub URL.

use std::fs;
use std::path::{Path, PathBuf};

use langs_in_rust::{languages, readme};

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

#[test]
fn renders_the_readme_the_way_python_did() {
    let languages = languages::load(&fixture(languages::PATH)).unwrap();
    let expected = fs::read_to_string(fixture(readme::PATH)).unwrap();

    assert_eq!(readme::render(&languages), expected);
}

#[test]
fn writes_the_language_list_the_way_python_did() {
    let expected = fs::read_to_string(fixture(languages::PATH)).unwrap();
    let languages = languages::load(&fixture(languages::PATH)).unwrap();

    assert_eq!(languages::to_json(&languages).unwrap(), expected);
}
